apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tusharchoudhary2002/students-backend:latest
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 3
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /health
              port: 8080

            failureThreshold: 30
            periodSeconds: 5

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

            requests:
              memory: "64Mi"
              cpu: "250m"

          volumeMounts:
            - name: backend-config
              mountPath: /app/config/local.yaml
              subPath: local.yaml

            - name: storage-volume
              mountPath: /app/storage

      volumes:
        - name: backend-config

          configMap:
            name: backend-config

        - name: storage-volume
          emptyDir: {}
